Issue #14261 - Incorrect WFP CTD timestamps and pressures
oceanobservatories/mi-instrument pull request #84
Opened 2020-09-02 17:17 UTC by steinermg

To adjust the timestamps generated from the "c" files (CTD and Dosta), the c file driver first invokes an "e" file driver to get a list of time-pressure tuples. The list is passed to the "c" file parser where pressures in the "c" samples and "e" samples are aligned to base the "c" file timestamps on the "e" file timestamps in the list.

2020-09-02 18:04 UTC, tlfish3638 requested changes
Changes generally look ok but you need to
a) add an update to RELEASE_NOTES.md
b) update version in setup.py
c) add Paul to the review so he's aware

Also, does the mi/core change require an update to the portland-05/06 machines?

2020-09-03 15:11 UTC, sgfoote approved these changes

2020-09-03 18:28 UTC, steinermg commented on mi/dataset/driver/ctdpf_ckl/wfp/ctdpf_ckl_wfp_driver.py
> +# Copyright 2014 Raytheon Co.
now updated to 2020

2020-09-03 18:29 UTC, steinermg commented on mi/dataset/driver/flort_kn/stc_imodem/flort_kn__stc_imodem_driver.py
> +@version("0.0.2")
Thanks for catching that. It is now changed to 0.0.1.

2020-09-03 18:41 UTC, pauldavidmena approved these changes
There's a lot going on there, but it looks good to me.

2020-09-03 19:02 UTC, tlfish3638 approved these changes
Thanks

2020-09-03 19:47 UTC, merged